#!/usr/bin/env python3
"""macOS menu bar app for MeroShare Auto-Apply.

Lives in the system menu bar and exposes the app without forcing a
browser tab to stay open. Talks to the Flask backend over the
existing /api/* endpoints; spawns Flask on demand.

The menu surfaces:
  - status header (version + scheduler / next-run summary)
  - per-issue submenu, click an issue to open it on the dashboard
  - per-account submenu with apply-now and login-test shortcuts
  - background scheduler toggle + interval picker
  - preferences (share types, kitta, launch-at-login)
  - update channel: notification + click-to-download

This module is macOS-only because rumps wraps Cocoa's NSStatusItem.
Requirements gates the dep with `; sys_platform == "darwin"`.
"""
from __future__ import annotations

import logging
import os
import subprocess
import sys
import threading
import time
import webbrowser
from pathlib import Path
from typing import Any

import requests
import rumps

import accounts
import notification_queue
from _version import __version__
from updater import check_for_updates, is_dev_build

BASE_DIR = Path(__file__).resolve().parent
PORT = int(os.environ.get("MEROSHARE_PORT") or "5050")
BASE_URL = f"http://localhost:{PORT}"

# Generated by scripts/build_dmg.sh; absent in dev mode (rumps falls
# back to title-only when no icon is supplied).
ICON_PATH = BASE_DIR / "static" / "menubar-icon.png"

# When the GUI's "Stop everything" / Quit route writes this file, the menu
# bar's tick picks it up, deletes it, and exits cleanly. Without it
# the menu bar would keep re-spawning Flask each time the user hits
# "Open Dashboard".
SHUTDOWN_SENTINEL = accounts.STATE_DIR / ".shutdown-requested"

# Single-instance lockfile. The bash launcher's pgrep dedup catches
# Login Item / Finder relaunches but is bypassed when the menu bar
# is started directly (e.g. by the LaunchAgent at login, which the
# Launch-at-login toggle installs and which invokes the bundled
# Python directly — not the bash launcher). flock is the only
# cross-launch-path defense: whichever Python process gets here
# first holds the lock; the second, third, ... open the dashboard
# and exit. Lives in STATE_DIR so it inherits the same path as the
# rest of the per-user state.
INSTANCE_LOCK_PATH = accounts.STATE_DIR / ".menubar-instance.lock"

# Apple's standard launchd location for per-user, on-login agents.
LAUNCH_AGENT_LABEL = "com.meroshare.menubar"
LAUNCH_AGENT_PATH = (
    Path.home() / "Library" / "LaunchAgents" / f"{LAUNCH_AGENT_LABEL}.plist"
)

# Marker file: when present, the menu bar app also shows up in the
# Dock and Cmd-Tab. Default state (no file) is menu-bar-only, matching
# Info.plist's LSUIElement=true. Lives in STATE_DIR so it survives
# bundle reinstalls.
SHOW_IN_DOCK_MARKER = accounts.STATE_DIR / ".show-in-dock"

UPDATE_CHECK_INTERVAL_S = 6 * 60 * 60
INITIAL_UPDATE_DELAY_S = 30
STATUS_REFRESH_INTERVAL_S = 30

# Most submenus are dynamic. Cap the number of children so a user
# with hundreds of historical applications doesn't blow up the menu.
MAX_ISSUES_IN_MENU = 20
MAX_ACCOUNTS_IN_MENU = 20

logger = logging.getLogger("meroshare.menubar")
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(message)s")


# NSApplicationActivationPolicy values, mirrored here so we don't
# have to import the AppKit constants at module load time (PyObjC
# imports are not free).
_NS_ACTIVATION_POLICY_REGULAR = 0    # Dock icon + Cmd-Tab + menu bar
_NS_ACTIVATION_POLICY_ACCESSORY = 1  # menu bar only (no Dock)


def _set_dock_visibility(visible: bool) -> None:
    """Toggle the Dock icon at runtime via NSApp.setActivationPolicy_.

    macOS lets a running app move between policies without a relaunch,
    so the Show-in-Dock toggle takes effect immediately. Setting
    .regular adds the Dock icon and a Cmd-Tab entry; .accessory hides
    them. The status item stays put either way.
    """
    try:
        from AppKit import NSApp
        policy = (
            _NS_ACTIVATION_POLICY_REGULAR if visible
            else _NS_ACTIVATION_POLICY_ACCESSORY
        )
        NSApp.setActivationPolicy_(policy)
    except Exception as e:
        logger.warning("Could not change activation policy: %s", e)


def _show_in_dock_enabled() -> bool:
    return SHOW_IN_DOCK_MARKER.exists()


def _show_in_dock_set(enabled: bool) -> None:
    """Persist the Dock-visibility preference and apply it now."""
    if enabled:
        SHOW_IN_DOCK_MARKER.parent.mkdir(parents=True, exist_ok=True)
        SHOW_IN_DOCK_MARKER.touch()
    else:
        try:
            SHOW_IN_DOCK_MARKER.unlink(missing_ok=True)
        except OSError as e:
            logger.debug("Could not remove dock marker: %s", e)
    _set_dock_visibility(enabled)


def _activate_foreground() -> None:
    """Pull the menu bar app to the foreground so modal dialogs are visible.

    macOS apps with LSUIElement=true (no Dock icon, just a menu bar
    item) routinely lose foreground state. NSAlert.runModal will
    happily display behind whatever window has focus, leaving the
    user staring at a frozen-looking menu bar. Calling
    activateIgnoringOtherApps_ right before the alert reliably brings
    the alert to the front. rumps.alert tries this internally but
    the timing races with menu dismissal, so we activate explicitly.
    """
    try:
        from AppKit import NSApp
        NSApp.activateIgnoringOtherApps_(True)
    except Exception as e:
        logger.debug("NSApp activation failed: %s", e)


def _osascript_dialog(title: str, message: str) -> None:
    """Last-resort dialog via osascript when rumps.alert silently fails.

    AppleScript dialogs are routed through the system event loop, so
    they bypass any quirks of our LSUIElement-true app. Slower to
    spawn (forks osascript) but always shows up.
    """
    # The escape sequence dance: AppleScript's display-dialog string
    # literal interprets `\n` as a newline and `\\` as a single
    # backslash. To pass a real newline through, the SHELL command
    # line must contain `\n` (two chars). _esc converts Python's real
    # newline char ('\n', U+000A) into the two-char `\\n` sequence
    # that AppleScript turns back into a newline.
    def _esc(s: str) -> str:
        return (
            s.replace("\\", "\\\\").replace('"', '\\"')
             .replace("\r", " ").replace("\n", "\\n")
        )
    # Use a REAL newline between title and message — _esc will then
    # produce the AppleScript escape sequence. The previous code
    # used `\\n\\n` (Python literal backslash-n) which got escaped
    # AGAIN by _esc into `\\\\n\\\\n` and showed up verbatim.
    body = f"{title}\n\n{message}" if title else message
    subprocess.run(
        ["osascript", "-e",
         f'display dialog "{_esc(body)}" buttons {{"OK"}} default button 1'],
        check=False, capture_output=True,
    )


def _show_dialog(title: str, message: str) -> None:
    """Display a modal dialog from the menu bar context.

    On macOS with LSUIElement=true (no Dock icon — our default), NSAlert
    routinely renders BEHIND the foreground app and the menu bar
    appears frozen because the alert is blocking the main run loop
    invisibly. `_activate_foreground` mitigates but doesn't always
    win the race against menu dismissal. Symptom: user clicks About,
    sees nothing, can't click anything else.

    Fix: prefer the osascript path on macOS — it routes through the
    system event loop, so it always renders on top. ~50ms slower
    (subprocess fork) but reliable. rumps.alert remains the fallback
    for the non-darwin case and as a last resort if osascript itself
    fails.

    When called from a background thread, dispatches back to the main
    thread because both AppKit and rumps wrap APIs that aren't thread-
    safe.
    """
    if threading.current_thread() is not threading.main_thread():
        # rumps.Timer fires on the main thread. A 0-delay one-shot is
        # the simplest "dispatch back to main" mechanism we have
        # without pulling in PyObjC's NSObject.performSelectorOnMainThread.
        timer = {"t": None}

        def _fire(_sender):
            if timer["t"]:
                timer["t"].stop()
            _show_dialog(title, message)

        timer["t"] = rumps.Timer(_fire, 0.01)
        timer["t"].start()
        return

    _activate_foreground()
    if sys.platform == "darwin":
        try:
            _osascript_dialog(title, message)
            return
        except Exception as e:
            logger.warning(
                "osascript dialog failed (%s); falling back to rumps.alert", e,
            )
    try:
        rumps.alert(title=title, message=message)
    except Exception as e:
        logger.warning("rumps.alert failed (%s)", e)


def _patch_rumps_notification() -> None:
    """Replace `rumps.notification` with an osascript-backed version.

    Module-level monkey-patch because notification calls are scattered
    across menubar.py and changing every call site is churn for a
    behavior change that's the same everywhere — fall back to
    osascript instead of trusting rumps's bundle lookup. Keeps the
    rumps API surface (title/subtitle/message/sound kwargs) so the
    rest of the file reads naturally.
    """
    def _patched(title="", subtitle="", message="", sound=False, **_):
        _native_notification(title=title, message=message, subtitle=subtitle)
    rumps.notification = _patched


def _native_notification(title: str, message: str = "", subtitle: str = "") -> None:
    """Fire a desktop notification via osascript.

    `rumps.notification` reads `CFBundleIdentifier` from
    `NSBundle.mainBundle()`, which for our exec-into-bundled-Python
    layout resolves to the bundled interpreter's `bin/` directory
    rather than the .app — rumps then raises and kills the calling
    thread on every fire. osascript routes notifications through the
    system event loop and doesn't care which binary's bundle is
    "main", so it Just Works for any process layout.

    The previous workaround (writing a stub Info.plist next to the
    bundled Python) confused `codesign --deep` — it treated the
    `bin/` directory as a sub-bundle to sign, which produced an
    invalid manifest that macOS Launch Services rejected at .app
    launch time. Removing the Info.plist plus this osascript path
    sidesteps both bugs.
    """
    def _esc(s: str) -> str:
        return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")
    cmd = f'display notification "{_esc(message)}" with title "{_esc(title)}"'
    if subtitle:
        cmd += f' subtitle "{_esc(subtitle)}"'
    try:
        subprocess.run(
            ["osascript", "-e", cmd],
            check=False, capture_output=True, timeout=5,
        )
    except Exception as e:
        logger.debug("osascript notification failed: %s", e)


def _format_relative(iso_str: str | None) -> str:
    """Render an ISO timestamp as 'Xm ago' / 'in Xh' / etc.

    Naive inputs are interpreted as Asia/Kathmandu (UTC+05:45) to
    match `auto_apply._normalize_applied_date`. Without this, a
    daemon on a non-NPT host reading naive scheduler timestamps
    would display "5h ago" off by the local TZ offset.
    """
    if not iso_str:
        return "unknown"
    try:
        from datetime import datetime, timezone, timedelta
        dt = datetime.fromisoformat(iso_str.replace(" ", "T"))
        if dt.tzinfo is None:
            # Match _normalize_applied_date's Asia/Kathmandu default.
            dt = dt.replace(tzinfo=timezone(timedelta(hours=5, minutes=45)))
        t = dt.timestamp()
    except (ValueError, TypeError):
        return iso_str
    delta = time.time() - t
    past = delta >= 0
    delta = abs(delta)
    if delta < 60:
        return "just now" if past else "in <1m"
    mins = int(delta // 60)
    if mins < 60:
        return f"{mins}m ago" if past else f"in {mins}m"
    hrs = int(mins // 60)
    if hrs < 24:
        return f"{hrs}h ago" if past else f"in {hrs}h"
    days = int(hrs // 24)
    return f"{days}d ago" if past else f"in {days}d"


def _format_amount(npr: int | float | None) -> str:
    if npr is None or npr == "" or npr == 0:
        return "no cap"
    try:
        return f"Rs. {int(npr):,}"
    except (TypeError, ValueError):
        return str(npr)


def _interval_label(hours: int) -> str:
    if hours == 1:
        return "Every hour"
    return f"Every {hours} hours"


# Predefined intervals offered in the scheduler submenu. The Flask
# scheduler accepts any 1..24 but the menu picker only needs the
# common buckets. Users wanting odd values can still set them via the
# GUI Settings tab.
SCHEDULE_INTERVAL_CHOICES = (1, 3, 6, 12, 24)


# Apply the osascript-based notification shim once at import time.
# Module-level so any code path firing notifications (including
# library code that grabs `rumps.notification` early) hits the
# patched version.
_patch_rumps_notification()


class MeroShareMenuBar(rumps.App):
    def __init__(self) -> None:
        # Icon-only menu bar in steady state: no "MS" or any acronym
        # next to the logo. During the brief cold-start window though,
        # we DO show "Starting…" text next to the icon so the user has
        # immediate visible feedback that double-clicking the .app
        # actually did something. `_auto_start_flask` clears the
        # title once Flask is reachable, returning to icon-only.
        # If the icon PNG is missing (broken install), rumps falls
        # back to the `name` as text — better than a blank slot the
        # user can't click on.
        icon_path = str(ICON_PATH) if ICON_PATH.exists() else None
        super().__init__(
            name="MeroShare",
            title=None if icon_path else "MeroShare",  # icon-only when icon present
            icon=icon_path,
            template=True,  # auto-invert for light/dark menu bars
            # Single "Quit" item (replaces the previous two-button
            # "Quit menu bar" + "Stop everything"). User mental model:
            # Quit = no menu bar = no app running. The handler stops
            # the scheduler, stops Flask, then exits the menubar
            # process — exactly the cleanup the previous "Stop
            # everything" did. We override quit_button=None because
            # we wire our own item below.
            quit_button=None,
        )

        # Long-lived state pulled from the API on each tick. Held on
        # self so submenu builders can read coherent snapshots without
        # re-fetching mid-render.
        self._scheduler_state: dict[str, Any] = {}
        self._issues_state: list[dict[str, Any]] = []
        self._accounts_state: list[dict[str, Any]] = []
        self._config_state: dict[str, Any] = {}
        self._update_info: dict[str, Any] | None = None

        # Spawned Flask process, when we started one. Used by "Stop
        # everything" to terminate the right tree.
        self._flask_proc: subprocess.Popen | None = None

        # NSApp doesn't exist until rumps.App.run() spins up the Cocoa
        # runloop, so anything that pokes NSApp (setActivationPolicy_,
        # setApplicationIconImage_) has to wait. We schedule the
        # application of these post-launch via a one-shot Timer that
        # fires once the runloop is alive. The previous form ran
        # _set_dock_visibility / _refresh_app_icon_image directly in
        # __init__ and silently swallowed an AttributeError on every
        # launch — both became no-ops, so Show-in-Dock didn't apply
        # and the notification icon cache never got refreshed.
        def _post_launch(_sender):
            self._post_launch_timer.stop()
            if _show_in_dock_enabled():
                _set_dock_visibility(True)
            self._refresh_app_icon_image()
        self._post_launch_timer = rumps.Timer(_post_launch, 0.1)
        self._post_launch_timer.start()

        # Build the menu structure once. Most items are stable; the
        # submenu contents get rebuilt by tick handlers as state
        # changes.
        self._build_menu()

        # Refresh + update timers. rumps.Timer fires on the main
        # thread, so each handler offloads HTTP to a background
        # thread to keep the menu responsive.
        self._refresh_timer = rumps.Timer(self._tick, STATUS_REFRESH_INTERVAL_S)
        self._refresh_timer.start()

        self._update_timer = rumps.Timer(
            self._update_tick, UPDATE_CHECK_INTERVAL_S,
        )
        self._update_timer.start()

        # Initial paint without waiting for the 30s tick.
        threading.Thread(target=self._refresh_all, daemon=True).start()
        threading.Timer(
            INITIAL_UPDATE_DELAY_S,
            lambda: threading.Thread(target=self._check_updates, daemon=True).start(),
        ).start()

        # Auto-start Flask on launch. Users mental-model is "open the
        # app → the app is running" — discovering they have to click
        # Open Dashboard to actually start anything was a real
        # user-reported confusion. We spawn it in the background so
        # the menu bar paints immediately while Flask cold-starts;
        # status header switches from "starting…" → "ready" once
        # /api/health responds.
        threading.Thread(target=self._auto_start_flask, daemon=True).start()

        # Notification drain. The Flask process can't fire notifications
        # with the .app's icon (it's detached from the bundle), so it
        # appends to a queue file and we — running inside the .app —
        # drain it and fire rumps.notification, which uses
        # NSUserNotification with the bundle's icon. 1.5s feels
        # immediate to the user without burning cycles.
        self._notify_drain_timer = rumps.Timer(self._drain_notifications, 1.5)
        self._notify_drain_timer.start()

        # Fast sentinel poll. The dashboard's "Stop everything" button
        # writes a sentinel file AND tries to SIGTERM us via pgrep —
        # but Python signal handlers are deferred until the VM yields,
        # and the rumps event loop spends most of its time in a Cocoa
        # runloop call where bytecode isn't running. The signal
        # handler can sit pending for tens of seconds, leaving the
        # menu bar visibly lingering after the user clicked Quit. A
        # rumps.Timer DOES fire on the runloop directly (via NSTimer),
        # so a 1-second sentinel check guarantees teardown within ~1s
        # regardless of signal-handler timing.
        self._sentinel_fast_timer = rumps.Timer(self._sentinel_check_tick, 1.0)
        self._sentinel_fast_timer.start()

        # NB: NSApp.setApplicationIconImage_ now runs from
        # _post_launch_timer above, after the Cocoa runloop is alive.
        # Calling it directly in __init__ (NSApp is None pre-run)
        # silently no-op'd on every launch.

        # SIGTERM handler: when the user clicks Settings → "Stop
        # everything" in the dashboard, /api/shutdown sends us SIGTERM
        # so the menu bar dies in lockstep with Flask. Without this,
        # the status item lingers up to 30 seconds (one sentinel tick).
        # Flask has already done the heavy cleanup (scheduler stop, its
        # own exit), so all we need to do here is release the
        # NSStatusItem and quit. We dispatch the actual quit on a
        # short-delay timer so signal handlers don't fight with the
        # rumps event loop directly.
        def _on_sigterm(_signum, _frame):
            logger.info("Received SIGTERM; shutting down menu bar.")
            # rumps.Timer fires on the main thread which is the safe
            # place to invoke quit_application. A bare 0.05s delay
            # gives the signal handler a chance to return cleanly.
            timer = {"t": None}

            def _fire(_sender):
                if timer["t"]:
                    timer["t"].stop()
                # Best-effort cleanup of the sentinel and any Flask
                # subprocess we spawned. Then exit. Mirrors what the
                # menu bar's "Quit" item does, minus the duplicate
                # /api/shutdown call (Flask is already shutting down
                # — that's WHY it sent us SIGTERM).
                try:
                    SHUTDOWN_SENTINEL.unlink(missing_ok=True)
                except OSError:
                    pass
                if self._flask_proc and self._flask_proc.poll() is None:
                    try:
                        self._flask_proc.terminate()
                    except OSError:
                        pass
                rumps.quit_application()

            timer["t"] = rumps.Timer(_fire, 0.05)
            timer["t"].start()

        try:
            import signal as _signal
            _signal.signal(_signal.SIGTERM, _on_sigterm)
        except (ValueError, OSError) as e:
            # Some embedded contexts (e.g. CI test harness) can't set
            # signal handlers. Fall through to the sentinel-tick path.
            logger.debug("Could not install SIGTERM handler: %s", e)

    # ── Menu construction ──────────────────────────────────────────

    def _build_menu(self) -> None:
        # Header items. read-only (no callback) so they render greyed
        # out and don't pretend to be actionable.
        self._header = rumps.MenuItem(f"MeroShare Auto-Apply v{__version__}")
        self._status_line = rumps.MenuItem("Status: starting…")
        self._next_run_line = rumps.MenuItem("Scheduler: -")
        self._issue_count_line = rumps.MenuItem("Open issues: -")

        # Update-available item appears at the top once a release is
        # detected; until then it just reads "Check for Updates…".
        self._update_item = rumps.MenuItem(
            "Check for Updates…", callback=self._on_check_updates,
        )

        # Submenus, built empty here and filled by refresh handlers.
        self._issues_menu = rumps.MenuItem("Open Issues")
        self._accounts_menu = rumps.MenuItem("Accounts")
        self._scheduler_menu = rumps.MenuItem("Background Scheduler")
        self._prefs_menu = rumps.MenuItem("Preferences")

        # Static actions.
        self._open_item = rumps.MenuItem(
            "Open Dashboard", callback=self._on_open_dashboard, key="o",
        )
        self._run_item = rumps.MenuItem(
            "Run Check Now", callback=self._on_run_check, key="r",
        )

        self.menu = [
            self._header,
            None,
            self._status_line,
            self._next_run_line,
            self._issue_count_line,
            None,
            self._open_item,
            self._run_item,
            None,
            self._issues_menu,
            self._accounts_menu,
            None,
            self._scheduler_menu,
            self._prefs_menu,
            None,
            self._update_item,
            rumps.MenuItem("About", callback=self._on_about),
            None,
            rumps.MenuItem("Quit", callback=self._on_quit, key="q"),
        ]

        # Initial scheduler-submenu skeleton (rebuilt per tick to
        # reflect the actual loaded state).
        self._build_scheduler_submenu(enabled=False, current_interval=None)
        self._build_prefs_submenu({})
        self._issues_menu.add(rumps.MenuItem("(loading…)"))
        self._accounts_menu.add(rumps.MenuItem("(loading…)"))

    # ── HTTP plumbing ──────────────────────────────────────────────

    def _flask_alive(self) -> bool:
        try:
            r = requests.get(f"{BASE_URL}/api/health", timeout=2)
            return r.status_code in (200, 503)
        except requests.RequestException:
            return False

    def _api(self, path: str, method: str = "GET", **kwargs):
        try:
            resp = requests.request(method, f"{BASE_URL}{path}", timeout=8, **kwargs)
            if not resp.ok:
                return None
            if resp.text:
                return resp.json()
            return {}
        except (requests.RequestException, ValueError) as e:
            logger.debug("%s %s failed: %s", method, path, e)
            return None

    def _ensure_flask(self) -> bool:
        """Start Flask if not already running. Returns True when reachable."""
        if self._flask_alive():
            return True
        python = sys.executable
        app_py = BASE_DIR / "app.py"
        if not app_py.exists():
            _show_dialog(
                "App files missing",
                f"app.py not found at {app_py}.\nRe-install the app.",
            )
            return False
        try:
            self._flask_proc = subprocess.Popen(
                [python, str(app_py)],
                cwd=str(BASE_DIR),
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                start_new_session=True,
            )
        except OSError as e:
            _show_dialog("Could not start app", str(e))
            return False
        # Poll up to 10s for the bind. Cold first-imports on the
        # bundled venv can take a couple of seconds.
        for _ in range(20):
            if self._flask_alive():
                return True
            time.sleep(0.5)
        _show_dialog(
            "App did not start",
            f"Flask is not responding on port {PORT}. See ~/Library/Logs/"
            "MeroShare Auto-Apply/menubar.log.",
        )
        return False

    def _auto_start_flask(self) -> None:
        """Spawn Flask quietly at app launch.

        Same code path as `_ensure_flask` but without the
        modal-dialog-on-failure UX — auto-start should never block the
        user with a popup at login. If Flask doesn't come up, the
        status line in the menu (`Status: app stopped`) and the
        first user click on Open Dashboard surface the failure
        clearly enough.

        We also defer slightly so the menu bar item is fully wired up
        before the bundled-Python import overhead hits — keeps the
        click-the-icon-and-see-the-menu latency minimal.
        """
        # Slight delay: lets the menu bar render before we burn CPU
        # on the cold Python boot. Imperceptible to the user, but
        # avoids a "click-and-spinner" experience right after login.
        time.sleep(0.5)
        if self._flask_alive():
            return
        python = sys.executable
        app_py = BASE_DIR / "app.py"
        if not app_py.exists():
            logger.warning("auto-start: app.py not found at %s", app_py)
            return
        try:
            self._flask_proc = subprocess.Popen(
                [python, str(app_py)],
                cwd=str(BASE_DIR),
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                start_new_session=True,
            )
            logger.info("Auto-started Flask (pid=%s)", self._flask_proc.pid)
        except OSError as e:
            logger.warning("auto-start: subprocess.Popen failed: %s", e)
            return
        # Poll for readiness so the next status tick paints "ready"
        # rather than "stopped" — but cap at 15s so a wedged Flask
        # doesn't hold the thread indefinitely.
        for _ in range(30):
            if self._flask_alive():
                logger.info("Flask reached /api/health on auto-start")
                # Clear the launch-time "Starting…" title so the menu
                # bar returns to icon-only (the user's preference for
                # steady state). Setting `title=None` rather than ""
                # is the rumps-native way to drop the text.
                if ICON_PATH.exists():
                    try:
                        # Clear the launch-time "Starting…" title so
                        # the menu bar settles to icon-only.
                        self.title = None
                    except Exception as e:
                        logger.debug("Could not clear menubar title: %s", e)
                # Trigger an immediate refresh so the status header
                # flips from "starting…" without waiting for the 30s
                # tick.
                threading.Thread(target=self._refresh_all, daemon=True).start()
                # Note: an explicit "MeroShare Auto-Apply is running"
                # notification was tried here. macOS auto-attaches a
                # "Show" action button to notifications from
                # LSUIElement apps that osascript can't suppress, and
                # it doesn't do anything useful (no main window to
                # bring forward). The menu bar transition from
                # "Starting…" → icon-only is the better feedback
                # mechanism: always visible, no actionable junk.
                return
            time.sleep(0.5)
        logger.warning(
            "auto-start: Flask didn't reach /api/health within 15s; "
            "status will reflect 'stopped' until next user action.",
        )
        # Failure path: keep the "M" anchor visible. The menu's
        # status header will flag "Status: app stopped" on its next
        # tick so the user has actionable feedback.
        if ICON_PATH.exists():
            try:
                self.title = None
            except Exception as e:
                logger.debug("Could not clear menubar title: %s", e)
        # When Flask doesn't bind in time, the menu's status header
        # paints "Status: app stopped" on its next tick — that's the
        # surface the user sees. We deliberately do NOT toast a
        # notification here either (same Show-button issue).

    # ── Tick handlers ──────────────────────────────────────────────

    def _tick(self, _sender) -> None:
        # Sentinel: the GUI's "Stop everything" route writes a file
        # we delete and exit on. TTL guard: a sentinel from a past
        # crash that wasn't cleaned up shouldn't block forever.
        # 5 minutes is more than enough margin for the GUI -> menu
        # bar tick delay (max 30s) but recognizes a stale file when
        # it sees one.
        SENTINEL_TTL_S = 5 * 60
        try:
            stat = SHUTDOWN_SENTINEL.stat()
        except FileNotFoundError:
            stat = None
        except OSError as e:
            logger.debug("Sentinel stat failed: %s", e)
            stat = None
        if stat is not None:
            age = time.time() - stat.st_mtime
            try:
                SHUTDOWN_SENTINEL.unlink()
            except OSError as e:
                logger.debug("Sentinel unlink failed: %s", e)
            if age <= SENTINEL_TTL_S:
                logger.info("Shutdown sentinel observed; exiting menu bar.")
                rumps.quit_application()
                return
            logger.info(
                "Ignoring stale shutdown sentinel (%.0fs old > %ds TTL).",
                age, SENTINEL_TTL_S,
            )
        threading.Thread(target=self._refresh_all, daemon=True).start()

    def _update_tick(self, _sender) -> None:
        threading.Thread(target=self._check_updates, daemon=True).start()

    def _sentinel_check_tick(self, _sender) -> None:
        """Fast-poll the shutdown sentinel that the dashboard's
        Stop-everything path writes. Runs on the rumps event loop, so
        it doesn't suffer from Python's signal-handler deferral when
        the main thread is parked in the Cocoa runloop.

        The 30-second main `_tick` also checks the sentinel as a
        backstop; this faster timer just makes the user-facing
        latency match the click-to-disappear UX they expect.
        """
        SENTINEL_TTL_S = 5 * 60
        try:
            stat = SHUTDOWN_SENTINEL.stat()
        except FileNotFoundError:
            return
        except OSError:
            return
        age = time.time() - stat.st_mtime
        if age >= SENTINEL_TTL_S:
            return  # stale from a past crash, ignore
        try:
            SHUTDOWN_SENTINEL.unlink()
        except OSError:
            pass
        logger.info("Shutdown sentinel observed (fast tick); exiting menu bar.")
        if self._flask_proc and self._flask_proc.poll() is None:
            try:
                self._flask_proc.terminate()
            except OSError:
                pass
        rumps.quit_application()

    def _refresh_app_icon_image(self) -> None:
        """Explicitly set NSApp.applicationIconImage from the bundle's
        icon.icns so notifications and the Dock show the correct logo.

        The bundle layout we expect:
            …/MeroShare Auto-Apply.app/Contents/Resources/icon.icns
            …/MeroShare Auto-Apply.app/Contents/Resources/app/menubar.py
        So `BASE_DIR.parent / "icon.icns"` is the icon.

        No-op if the icon file isn't where we expect (dev mode running
        from source has no .icns; that's fine — the menu bar template
        PNG is its own thing). Failures are swallowed — a wrong icon
        is cosmetic, but a startup crash would be fatal.
        """
        try:
            bundle_icns = BASE_DIR.parent / "icon.icns"
            if not bundle_icns.exists():
                return
            from AppKit import NSApp, NSImage
            img = NSImage.alloc().initByReferencingFile_(str(bundle_icns))
            if img:
                NSApp.setApplicationIconImage_(img)
                logger.info("Registered bundle icon for notifications + Dock.")
        except Exception as e:
            logger.debug("Could not refresh app icon image: %s", e)

    def _drain_notifications(self, _sender) -> None:
        """Pull queued notifications from the cross-process JSONL queue
        and fire each as a native NSUserNotification.

        The Flask process can't fire these directly with the right icon
        (it's a subprocess detached from the .app bundle), so it appends
        to the queue and we — owning the bundle — drain. Failures are
        swallowed: a notification that doesn't fire is far better than
        a menu bar that crashes because Notification Center is acting
        up.
        """
        try:
            entries = notification_queue.drain()
        except Exception as e:
            logger.debug("Notification drain failed: %s", e)
            return
        for entry in entries:
            try:
                rumps.notification(
                    title=entry.get("title") or "MeroShare Auto-Apply",
                    subtitle="",
                    message=entry.get("message") or "",
                    sound=False,
                )
            except Exception as e:
                logger.debug("rumps.notification failed: %s", e)

    # ── State refresh ──────────────────────────────────────────────

    def _refresh_all(self) -> None:
        """Pull state from the Flask API and update the menu in place."""
        flask_alive = self._flask_alive()
        if not flask_alive:
            self._render_offline()
            self._was_offline = True
            return

        # Detect the offline → online transition. After _render_offline,
        # all four submenus carry the "(app stopped)" placeholder and
        # the cached states are zeroed. If the next /api response
        # happens to also be empty (e.g. /api/scheduler returns {}
        # because we hit it during a brief Flask cold-start window
        # where some endpoints aren't ready), the equality short-
        # circuits below would skip the repaint and leave the
        # placeholders stuck — exactly the bug the user reported.
        # Force a full repaint on the transition.
        was_offline = getattr(self, "_was_offline", True)
        self._was_offline = False

        # All four endpoints are local and cheap; fetch sequentially
        # to keep the rumps menu stable (avoid mutations from N
        # concurrent threads).
        new_scheduler = self._api("/api/scheduler") or {}
        new_accounts = self._api("/api/accounts") or []
        issues_resp = self._api("/api/issues") or {}
        # /api/issues returns {"issues": [...]} on the happy path, but a
        # cold-start Flask can briefly return {}. The `or []` here
        # handles both: missing key → None → [], and non-dict → bare
        # list. The previous form left `or []` only on the else
        # branch and let None leak through to _render_status_lines.
        if isinstance(issues_resp, dict):
            new_issues = issues_resp.get("issues") or []
        else:
            new_issues = issues_resp or []
        new_config = self._api("/api/config") or {}

        # Skip rebuilding submenus whose source data is byte-for-byte
        # identical to what we last rendered. Avoids menu flicker if
        # the user has the menu open during a tick. On the offline →
        # online transition, force a repaint regardless.
        sched_changed = was_offline or new_scheduler != self._scheduler_state
        accts_changed = was_offline or new_accounts != self._accounts_state
        issues_changed = was_offline or new_issues != self._issues_state
        config_changed = was_offline or new_config != self._config_state

        self._scheduler_state = new_scheduler
        self._accounts_state = new_accounts
        self._issues_state = new_issues
        self._config_state = new_config

        # Status lines are cheap; always re-render so "X minutes ago"
        # ticks forward.
        self._render_status_lines()
        if issues_changed:
            self._render_issues_submenu()
        if accts_changed:
            self._render_accounts_submenu()
        if sched_changed:
            self._render_scheduler_submenu()
        if config_changed or sched_changed:
            self._render_prefs_submenu()

    def _render_offline(self) -> None:
        self._status_line.title = "Status: starting…"
        self._next_run_line.title = "Scheduler: -"
        self._issue_count_line.title = "Open issues: -"
        # Only reset the submenus whose CONTENT depends on a live
        # Flask response: Open Issues (needs /api/issues) and Accounts
        # (needs /api/accounts). Scheduler and Preferences are
        # config-driven; their last-known state from /api/config or
        # the empty-state __init__ paint is more useful than a
        # "(app stopped)" placeholder that gets stuck if a subsequent
        # refresh's data happens to be byte-equal.
        # The status header above already conveys "Status: starting…"
        # so the user knows things are coming up — duplicating that
        # message inside every submenu is noise.
        self._reset_submenu(self._issues_menu, "(starting…)")
        self._reset_submenu(self._accounts_menu, "(starting…)")
        # Drop our cached state for the Flask-dependent submenus so
        # the next online tick rebuilds them from scratch (the equality
        # short-circuits in _refresh_all would otherwise compare
        # against stale state).
        self._issues_state = []
        self._accounts_state = []
        # The "Update Available" item title is sticky between
        # update-check ticks. If we previously detected an update and
        # then went offline, the title stays "Update Available: vX →"
        # until the next successful check. Reset to the neutral
        # title so a stale update prompt doesn't confuse the user.
        if self._update_info is None:
            self._update_item.title = "Check for Updates…"

    def _render_status_lines(self) -> None:
        sched = self._scheduler_state
        if sched.get("enabled"):
            interval = sched.get("interval_hours")
            last = sched.get("last_result") or "no runs yet"
            self._status_line.title = (
                f"Status: scheduler on, every {interval}h"
            )
            last_run = sched.get("last_run")
            next_run = sched.get("next_run")
            parts = []
            if last_run:
                parts.append(f"last run {_format_relative(last_run)}")
            if next_run:
                parts.append(f"next {_format_relative(next_run)}")
            if last and len(last) <= 80:
                parts.append(last)
            self._next_run_line.title = "  " + (" · ".join(parts) or "-")
        else:
            self._status_line.title = "Status: scheduler off"
            self._next_run_line.title = "  not scheduled"

        # Issue count read from the per-account response; sum unique
        # companyShareIds so a single issue applicable to N accounts
        # counts once.
        unique = {
            str(i.get("companyShareId") or i.get("id") or "")
            for i in self._issues_state if i
        } - {""}
        self._issue_count_line.title = f"Open issues: {len(unique)}"

    # ── Issues submenu ─────────────────────────────────────────────

    def _render_issues_submenu(self) -> None:
        self._reset_submenu(self._issues_menu)
        issues = self._issues_state or []
        if not issues:
            self._issues_menu.add(rumps.MenuItem("(no open issues)"))
            return
        # Dedupe by companyShareId so a multi-account workspace
        # doesn't repeat the same issue per account in the menu.
        seen: set[str] = set()
        rendered = 0
        for issue in issues:
            iid = str(issue.get("companyShareId") or issue.get("id") or "")
            if not iid or iid in seen:
                continue
            seen.add(iid)
            self._issues_menu.add(self._build_issue_menu_item(issue))
            rendered += 1
            if rendered >= MAX_ISSUES_IN_MENU:
                self._issues_menu.add(rumps.MenuItem(
                    f"… and {len(issues) - rendered} more",
                ))
                break

    def _build_issue_menu_item(self, issue: dict) -> rumps.MenuItem:
        # The /api/issues route normalizes raw MeroShare field names
        # into shorter ones (`company`, `shareType`) — the menubar
        # was previously reading the raw names and getting "?" for
        # everything. Try the normalized name first, then fall back
        # to the raw MeroShare name in case a future caller (e.g.
        # locally-cached records) supplies the unnormalized shape.
        company = (
            issue.get("company")
            or issue.get("companyName")
            or "?"
        )
        share_type = (
            issue.get("shareType")
            or issue.get("shareTypeName")
            or ""
        )
        # "?" share types are placeholders the API uses when it can't
        # classify; suppress them in the menu so the title stays clean.
        if share_type == "?":
            share_type = ""
        title = company if not share_type else f"{company} ({share_type})"
        item = rumps.MenuItem(title)

        # Per-account application chips. The /api/issues route returns
        # `applications` as a {account_id: {applied: bool, …}} dict.
        # Fall back to the older `accountChips` / `chips` shapes for
        # forward-compat.
        applications = issue.get("applications")
        if isinstance(applications, dict):
            total = len(applications)
            applied = sum(1 for a in applications.values()
                          if isinstance(a, dict) and a.get("applied"))
        else:
            chips = issue.get("accountChips") or issue.get("chips") or []
            applied = sum(1 for c in chips if c.get("state") == "applied")
            total = len(chips)
        if total:
            item.add(rumps.MenuItem(f"{applied}/{total} accounts applied"))

        iid = issue.get("id") or issue.get("companyShareId")

        def _open(_sender, _iid=iid):
            self._on_open_issue(_iid)

        item.add(rumps.MenuItem("Open on dashboard", callback=_open))
        return item

    # ── Accounts submenu ───────────────────────────────────────────

    def _render_accounts_submenu(self) -> None:
        self._reset_submenu(self._accounts_menu)
        accts = self._accounts_state or []
        if not accts:
            self._accounts_menu.add(
                rumps.MenuItem("(no accounts configured)", callback=self._on_open_settings),
            )
            return
        for a in accts[:MAX_ACCOUNTS_IN_MENU]:
            self._accounts_menu.add(self._build_account_menu_item(a))
        if len(accts) > MAX_ACCOUNTS_IN_MENU:
            self._accounts_menu.add(rumps.MenuItem(
                f"… and {len(accts) - MAX_ACCOUNTS_IN_MENU} more",
            ))
        self._accounts_menu.add(None)
        self._accounts_menu.add(rumps.MenuItem(
            "Manage accounts…", callback=self._on_open_settings,
        ))

    def _build_account_menu_item(self, acct: dict) -> rumps.MenuItem:
        name = acct.get("name", "?")
        item = rumps.MenuItem(name)
        dp = acct.get("dp_id", "?")
        boid = acct.get("username", "?")
        item.add(rumps.MenuItem(f"DP {dp} · BOID {boid}"))

        bank = acct.get("preferred_bank")
        if bank:
            item.add(rumps.MenuItem(f"Bank: {bank}"))

        aid = acct.get("id")

        def _test(_sender, _aid=aid):
            self._on_test_account(_aid)

        item.add(None)
        item.add(rumps.MenuItem("Test login", callback=_test))
        return item

    # ── Scheduler submenu ──────────────────────────────────────────

    def _render_scheduler_submenu(self) -> None:
        self._build_scheduler_submenu(
            enabled=bool(self._scheduler_state.get("enabled")),
            current_interval=self._scheduler_state.get("interval_hours"),
        )

    def _build_scheduler_submenu(self, *, enabled: bool, current_interval: int | None) -> None:
        self._reset_submenu(self._scheduler_menu)
        toggle = rumps.MenuItem(
            "Run in the background",
            callback=self._on_toggle_scheduler,
        )
        toggle.state = 1 if enabled else 0
        self._scheduler_menu.add(toggle)
        self._scheduler_menu.add(None)

        # Interval picker: each item is a checkable choice. Clicking
        # (re)starts the agent at the chosen interval.
        active = current_interval if enabled else None
        for hours in SCHEDULE_INTERVAL_CHOICES:
            label = _interval_label(hours)
            item = rumps.MenuItem(
                label, callback=self._make_interval_callback(hours),
            )
            item.state = 1 if active == hours else 0
            self._scheduler_menu.add(item)

    def _make_interval_callback(self, hours: int):
        def _cb(_sender):
            threading.Thread(
                target=self._set_scheduler,
                args=(True, hours),
                daemon=True,
            ).start()
        return _cb

    # ── Preferences submenu ────────────────────────────────────────

    def _render_prefs_submenu(self) -> None:
        self._build_prefs_submenu(self._config_state)

    def _build_prefs_submenu(self, config: dict) -> None:
        self._reset_submenu(self._prefs_menu)
        share_types = (config.get("share_types") or {}) if config else {}

        for key, label, default in (
            ("ipo_ordinary", "Auto-apply IPOs", True),
            ("right_share", "Auto-apply Right Shares", True),
            ("fpo", "Auto-apply FPOs", False),
            ("mutual_fund", "Auto-apply Mutual Funds", False),
            ("debenture", "Auto-apply Debentures", False),
        ):
            item = rumps.MenuItem(
                label, callback=self._make_share_type_callback(key),
            )
            current = share_types.get(key, default)
            item.state = 1 if current else 0
            self._prefs_menu.add(item)

        self._prefs_menu.add(None)

        auto = (config.get("auto_apply") or {}) if config else {}
        self._prefs_menu.add(rumps.MenuItem(
            f"Default kitta: {auto.get('default_kitta', 10)}",
        ))
        self._prefs_menu.add(rumps.MenuItem(
            f"Max amount: {_format_amount(auto.get('max_amount'))}",
        ))
        self._prefs_menu.add(rumps.MenuItem(
            "Edit in Settings…", callback=self._on_open_settings,
        ))

        self._prefs_menu.add(None)
        launch_item = rumps.MenuItem(
            "Launch at login", callback=self._on_toggle_launch_at_login,
        )
        launch_item.state = 1 if _launch_at_login_enabled() else 0
        self._prefs_menu.add(launch_item)

        dock_item = rumps.MenuItem(
            "Show in Dock", callback=self._on_toggle_show_in_dock,
        )
        dock_item.state = 1 if _show_in_dock_enabled() else 0
        self._prefs_menu.add(dock_item)

    def _make_share_type_callback(self, key: str):
        def _cb(_sender):
            threading.Thread(
                target=self._toggle_share_type,
                args=(key,),
                daemon=True,
            ).start()
        return _cb

    # ── Helpers ────────────────────────────────────────────────────

    @staticmethod
    def _reset_submenu(menu: rumps.MenuItem, placeholder: str | None = None) -> None:
        for key in list(menu.keys()):
            del menu[key]
        if placeholder:
            menu.add(rumps.MenuItem(placeholder))

    # ── Click handlers ─────────────────────────────────────────────

    _opening_dashboard = False  # class-level dedup flag for click pile-up

    def _on_open_dashboard(self, _sender) -> None:
        # Dedup rapid clicks. Without this, three quick clicks would
        # spawn three threads each waiting up to 10s for Flask to bind.
        if MeroShareMenuBar._opening_dashboard:
            return
        MeroShareMenuBar._opening_dashboard = True
        threading.Thread(target=self._open_dashboard_async, daemon=True).start()

    def _open_dashboard_async(self) -> None:
        try:
            if self._ensure_flask():
                webbrowser.open(BASE_URL)
        finally:
            MeroShareMenuBar._opening_dashboard = False

    def _on_open_settings(self, _sender) -> None:
        threading.Thread(
            target=lambda: (
                self._ensure_flask() and webbrowser.open(f"{BASE_URL}/settings")
            ),
            daemon=True,
        ).start()

    def _on_open_issue(self, issue_id) -> None:
        # Use the dashboard's hash-router so the URL deep-links to the
        # specific issue. The frontend reads `#dashboard?issue=<id>`
        # and scrolls / highlights the matching row. Falling back to
        # plain dashboard root when issue_id is missing.
        if issue_id:
            url = f"{BASE_URL}/#dashboard?issue={issue_id}"
        else:
            url = BASE_URL
        threading.Thread(
            target=lambda u=url: self._ensure_flask() and webbrowser.open(u),
            daemon=True,
        ).start()

    def _on_run_check(self, _sender) -> None:
        threading.Thread(target=self._run_check_async, daemon=True).start()

    def _run_check_async(self) -> None:
        if not self._ensure_flask():
            return
        result = self._api("/api/run-check", method="POST")
        if result is None:
            rumps.notification(
                title="MeroShare", subtitle="",
                message="Could not start check; see logs.",
            )
            return
        if result.get("error"):
            rumps.notification(
                title="MeroShare", subtitle="", message=result["error"],
            )
            return
        rumps.notification(
            title="MeroShare", subtitle="",
            message="Check started in the background.",
        )
        # Refresh the status panel a few seconds later so the user
        # sees the running state reflected without manually reopening
        # the menu.
        threading.Timer(3.0, self._tick, args=(None,)).start()

    def _on_test_account(self, account_id) -> None:
        # Show an immediate "testing…" notification so the user
        # knows the click registered. The login request can take
        # 5-15 seconds against MeroShare's WAF, and a silent menu
        # would feel broken.
        rumps.notification(
            title="MeroShare", subtitle="",
            message=f"Testing login for account {account_id}…",
        )

        def _go():
            if not self._ensure_flask():
                return
            result = self._api(
                f"/api/accounts/{account_id}/test-login", method="POST",
            )
            if result and result.get("success"):
                rumps.notification(
                    title="Login OK", subtitle="",
                    message=f"BOID {result.get('boid', '?')} verified.",
                )
            else:
                msg = (result or {}).get("error", "Login failed")
                rumps.notification(
                    title="Login failed", subtitle="", message=msg,
                )
        threading.Thread(target=_go, daemon=True).start()

    def _on_toggle_scheduler(self, _sender) -> None:
        currently_on = bool(self._scheduler_state.get("enabled"))
        if currently_on:
            threading.Thread(
                target=self._set_scheduler, args=(False, None), daemon=True,
            ).start()
        else:
            interval = (
                self._scheduler_state.get("interval_hours")
                or (self._config_state.get("check_interval_hours") if self._config_state else None)
                or 6
            )
            threading.Thread(
                target=self._set_scheduler, args=(True, interval), daemon=True,
            ).start()

    def _set_scheduler(self, enabled: bool, interval: int | None) -> None:
        if not self._ensure_flask():
            return
        if enabled:
            self._api(
                "/api/scheduler/start", method="POST",
                json={"interval_hours": interval},
            )
        else:
            self._api("/api/scheduler/stop", method="POST", json={})
        self._refresh_all()

    def _toggle_share_type(self, key: str) -> None:
        if not self._ensure_flask():
            return
        cfg = self._api("/api/config") or {}
        # Restrict the POST body to the keys the server-side
        # _validate_config knows about. Sending the full GET response
        # back could include fields like notifications.log_file that
        # the validator rejects, which would silently drop the
        # toggle.
        share_types = dict(cfg.get("share_types") or {})
        share_types[key] = not share_types.get(key, False)
        new_cfg: dict = {
            "share_types": share_types,
        }
        for top_level in ("auto_apply", "check_interval_hours", "notifications"):
            if top_level in cfg:
                new_cfg[top_level] = cfg[top_level]
        result = self._api("/api/config", method="POST", json=new_cfg)
        if result is None or (isinstance(result, dict) and result.get("error")):
            err = (result or {}).get("error", "Unknown error")
            rumps.notification(
                title="Could not update preferences",
                subtitle="", message=str(err),
            )
        self._refresh_all()

    def _on_toggle_launch_at_login(self, _sender) -> None:
        threading.Thread(
            target=self._toggle_launch_at_login, daemon=True,
        ).start()

    def _toggle_launch_at_login(self) -> None:
        if _launch_at_login_enabled():
            _launch_at_login_disable()
        else:
            _launch_at_login_enable()
        # Trigger a state refresh so the checkmark updates.
        self._render_prefs_submenu()

    def _on_toggle_show_in_dock(self, _sender) -> None:
        # Toggle synchronously: the activation policy change is a
        # cheap Cocoa call, no need to thread it. Doing it on the
        # main thread also keeps the immediate UI feedback (Dock
        # icon appearing) in lock-step with the menu state update.
        new_state = not _show_in_dock_enabled()
        _show_in_dock_set(new_state)
        self._render_prefs_submenu()
        rumps.notification(
            title="MeroShare",
            subtitle="",
            message=(
                "Now visible in Dock and Cmd-Tab."
                if new_state
                else "Hidden from Dock. Use the menu bar icon."
            ),
        )

    def _on_about(self, _sender) -> None:
        _show_dialog(
            "MeroShare Auto-Apply",
            (
                f"Version {__version__}\n"
                "Personal NEPSE share auto-applier.\n\n"
                "https://github.com/OfficialBishal/MeroShare-Auto-Apply"
            ),
        )

    def _on_quit(self, _sender) -> None:
        # Single "Quit" item. User mental model: no menu bar = no app
        # running. We stop the scheduler, shut down Flask, then exit
        # the menubar process. Confirmation prompt because tearing the
        # scheduler down silently would be a real foot-gun: the user
        # wouldn't notice their scheduled checks stopped firing for
        # hours or days.
        response = rumps.alert(
            title="Quit MeroShare Auto-Apply?",
            message=(
                "Quits the menu bar app, the dashboard server, AND "
                "the background scheduler. You'll need to re-launch "
                "the app to resume scheduled checks."
            ),
            ok="Quit",
            cancel="Cancel",
        )
        # rumps.alert returns 1 on OK, 0 on cancel.
        if response != 1:
            return
        threading.Thread(target=self._stop_everything, daemon=True).start()

    def _stop_everything(self) -> None:
        if self._flask_alive():
            # POST /api/shutdown handles scheduler.stop() AND writes
            # the sentinel AND fires SIGINT to its own process. We
            # only need to wait briefly for the response and the
            # process to actually go down.
            self._api("/api/shutdown", method="POST")
            for _ in range(10):
                if not self._flask_alive():
                    break
                time.sleep(0.3)

        # Belt-and-braces: if Flask was already alive when the menu
        # bar started, _flask_proc is None and we can't terminate it
        # via Popen. As a fallback, find any python listening on PORT
        # and SIGTERM it. Doing this only after /api/shutdown has had
        # its chance avoids a redundant kill in the normal case.
        if self._flask_alive():
            self._kill_flask_by_port()

        # If we DID spawn Flask ourselves, terminate the child too.
        if self._flask_proc and self._flask_proc.poll() is None:
            try:
                self._flask_proc.terminate()
            except OSError:
                pass

        # /api/shutdown wrote the sentinel for the menu bar to pick
        # up; clean it up since we're exiting deliberately.
        try:
            SHUTDOWN_SENTINEL.unlink(missing_ok=True)
        except OSError:
            pass
        rumps.quit_application()

    @staticmethod
    def _kill_flask_by_port() -> None:
        """Find and SIGTERM whatever owns PORT.

        Used by Stop-everything when the menu bar didn't spawn the
        Flask process itself (so `_flask_proc` is None) but Flask is
        still running. `lsof -ti :PORT` returns the PIDs cleanly.
        """
        # `lsof` lives at /usr/sbin/lsof on older macOS and
        # /usr/bin/lsof on modern. Let PATH resolve so we don't
        # hardcode the wrong path.
        try:
            res = subprocess.run(
                ["lsof", "-ti", f":{PORT}"],
                check=False, capture_output=True, text=True, timeout=2,
            )
        except (OSError, subprocess.TimeoutExpired):
            return
        for pid_str in (res.stdout or "").split():
            try:
                pid = int(pid_str)
            except ValueError:
                continue
            try:
                os.kill(pid, 15)  # SIGTERM
            except OSError:
                pass

    # ── Update check ───────────────────────────────────────────────

    def _check_updates(self, *, manual: bool = False) -> None:
        if is_dev_build(__version__) and not manual:
            return
        info = check_for_updates(__version__)
        if info is None:
            # Clear stale "Update Available" title in case a previous
            # tick saw an update that has since been superseded by the
            # user installing it.
            if self._update_info is not None:
                self._update_info = None
                self._update_item.title = "Check for Updates…"
            if manual:
                if is_dev_build(__version__):
                    _show_dialog(
                        "Development build",
                        (
                            f"Running {__version__}.\n\n"
                            "Update checks are disabled for unstamped builds. "
                            "Tag a release on GitHub to publish a versioned build."
                        ),
                    )
                else:
                    _show_dialog(
                        "Up to date",
                        f"You're running {__version__}.",
                    )
            return
        self._update_info = info
        self._update_item.title = f"Update Available: v{info['version']} →"
        if manual:
            self._open_update_url()
        else:
            rumps.notification(
                title="MeroShare update available",
                subtitle=f"v{info['version']}",
                message="Click the menu bar icon to download.",
            )

    def _open_update_url(self) -> None:
        if not self._update_info:
            return
        url = self._update_info.get("asset_url") or self._update_info["url"]
        webbrowser.open(url)

    def _on_check_updates(self, _sender) -> None:
        if self._update_info:
            self._open_update_url()
        else:
            threading.Thread(
                target=self._check_updates,
                kwargs={"manual": True},
                daemon=True,
            ).start()


# ── Launch-at-login helpers ────────────────────────────────────────

def _launch_at_login_enabled() -> bool:
    return LAUNCH_AGENT_PATH.exists()


def _launch_at_login_enable() -> None:
    """Install a LaunchAgent so the menu bar starts at login.

    The plist references this script via the running Python's path
    so dev-mode and bundled-mode both register correctly. Installs to
    ~/Library/LaunchAgents (per-user, no admin rights required).

    Idempotent: if the agent is already loaded, unloads first so the
    new plist takes effect.
    """
    from xml.sax.saxutils import escape as _xml_escape

    # macOS file paths can technically contain <, >, &, " — rare in
    # $HOME but defensive escaping prevents an unparseable plist if a
    # user has such a path.
    python = _xml_escape(sys.executable)
    script = _xml_escape(str(BASE_DIR / "menubar.py"))
    state_dir = _xml_escape(str(accounts.STATE_DIR))
    label = _xml_escape(LAUNCH_AGENT_LABEL)

    plist = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{label}</string>
    <key>ProgramArguments</key>
    <array>
        <string>{python}</string>
        <string>{script}</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <false/>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin</string>
        <key>MEROSHARE_DATA_DIR</key>
        <string>{state_dir}</string>
    </dict>
</dict>
</plist>
"""
    LAUNCH_AGENT_PATH.parent.mkdir(parents=True, exist_ok=True)
    # Idempotency: if a previous install is loaded, unload it before
    # replacing the plist. Otherwise launchctl will silently keep
    # running the old one.
    if LAUNCH_AGENT_PATH.exists():
        subprocess.run(
            ["launchctl", "unload", str(LAUNCH_AGENT_PATH)],
            check=False, capture_output=True,
        )
    LAUNCH_AGENT_PATH.write_text(plist)
    result = subprocess.run(
        ["launchctl", "load", str(LAUNCH_AGENT_PATH)],
        check=False, capture_output=True, text=True,
    )
    if result.returncode == 0:
        logger.info("Launch agent installed: %s", LAUNCH_AGENT_PATH)
    else:
        logger.warning(
            "launchctl load returned %d: %s",
            result.returncode, (result.stderr or "").strip(),
        )
    rumps.notification(
        title="Launch at login enabled", subtitle="",
        message="MeroShare will appear in your menu bar on next sign-in.",
    )


def _launch_at_login_disable() -> None:
    if LAUNCH_AGENT_PATH.exists():
        subprocess.run(
            ["launchctl", "unload", str(LAUNCH_AGENT_PATH)],
            check=False, capture_output=True,
        )
        try:
            LAUNCH_AGENT_PATH.unlink()
        except OSError:
            pass
    rumps.notification(
        title="Launch at login disabled", subtitle="",
        message="MeroShare will no longer auto-start.",
    )


# Holds the open file descriptor for INSTANCE_LOCK_PATH for the
# lifetime of the process. Module-level so it isn't garbage-collected
# (which would close the fd and release the flock). Never close it
# explicitly — the OS releases the lock when the process exits.
_INSTANCE_LOCK_FD: int | None = None


def _acquire_single_instance_lock() -> bool:
    """Take an exclusive non-blocking flock on INSTANCE_LOCK_PATH.

    Returns True if this process is the sole instance and may proceed,
    False if another menubar.py is already running and we should bail.

    The file is intentionally NOT removed on exit. flock semantics
    free the lock when the holding fd is closed (process death does
    this automatically), and leaving the inode in place lets the next
    launch grab the same lock atomically without the unlink/recreate
    race window.
    """
    global _INSTANCE_LOCK_FD
    import fcntl  # POSIX-only; macOS-targeted module is fine
    try:
        accounts.STATE_DIR.mkdir(parents=True, exist_ok=True)
        fd = os.open(str(INSTANCE_LOCK_PATH), os.O_CREAT | os.O_RDWR, 0o600)
    except OSError as exc:
        # Couldn't even create the lockfile (FS full, no perms). Be
        # permissive: dedup is best-effort, not load-bearing for
        # correctness, and bailing here would leave the user without
        # a menu bar at all.
        logger.warning("Instance lock unavailable; proceeding without dedup: %s", exc)
        return True
    try:
        fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except OSError:
        # Another instance already holds the lock.
        os.close(fd)
        return False
    # Stash the holder's pid for diagnostics. Truncate first so a
    # crashed predecessor's pid doesn't linger.
    try:
        os.ftruncate(fd, 0)
        os.write(fd, f"{os.getpid()}\n".encode())
    except OSError:
        pass
    _INSTANCE_LOCK_FD = fd
    return True


def main() -> None:
    if not _acquire_single_instance_lock():
        # Another menu bar instance is up. Mirror the bash launcher's
        # existing-instance branch (open dashboard, exit cleanly) so
        # the user gets visible feedback regardless of which launch
        # path won the race.
        logger.info(
            "Another menu bar instance holds %s; opening dashboard and exiting.",
            INSTANCE_LOCK_PATH,
        )
        try:
            webbrowser.open(BASE_URL, new=2)
        except Exception:
            pass
        return
    MeroShareMenuBar().run()


if __name__ == "__main__":
    main()
