#!/bin/bash
# Build a distributable .dmg for macOS. Fully self-contained.
#
# Output: dist/MeroShare-Auto-Apply.dmg (~70-100 MB)
#
# The .dmg bundles a relocatable Python interpreter (via the
# python-build-standalone project) and pre-installs every Python
# dependency (Flask, Playwright, requests, schedule, etc.) into the
# bundle. The recipient does NOT need Python on their system.
#
# What the recipient still needs: ~1 minute of internet on first
# launch, because Playwright's Chromium browser engine (~150MB) is
# downloaded to ~/Library/Caches/ms-playwright/ on demand. Bundling
# Chromium would push the .dmg past 200MB and bind us to the version
# we shipped. Letting Playwright fetch it keeps the bundle small
# and the browser fresh.
#
# Requirements:
#   - macOS (uses hdiutil, iconutil, sips, plutil. Built in)
#   - Internet on the build machine (downloads python-build-standalone
#     and Python deps; both are cached so subsequent builds are fast)
#   - Optional: `brew install create-dmg` for a prettier .dmg layout
#
# Architecture:
#   The build is per-arch. Running on an arm64 Mac produces an arm64
#   .dmg, on Intel an x86_64 .dmg. To distribute to both, run this
#   script on each host arch separately (or build with universal2
#   Python. Skipped here for size reasons).
#
# Code signing / notarization:
#   The build is UNSIGNED. macOS Gatekeeper will block first launch
#   with "unidentified developer". Workaround for the user: right-
#   click the .app → Open → Open. After the first time, double-click
#   works. To eliminate the prompt, sign with a Developer ID
#   certificate ($99/year Apple Developer Program). See the README.

set -euo pipefail

# ── Paths ────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BUILD_DIR="$PROJECT_ROOT/build"
DIST_DIR="$PROJECT_ROOT/dist"
APP_NAME="MeroShare Auto-Apply"
APP_BUNDLE="$BUILD_DIR/$APP_NAME.app"
DMG_NAME="MeroShare-Auto-Apply.dmg"
DMG_PATH="$DIST_DIR/$DMG_NAME"

# Version resolution priority:
#   1. GITHUB_REF_NAME. Set by GitHub Actions on tag pushes (`v2026.05.04`)
#   2. `git describe --tags --exact-match`. Local tag-build
#   3. `<date>+dev`. Local untagged build; the `+dev` suffix tells the
#      menu bar's auto-updater to skip prompts (contributor running
#      from source shouldn't be nagged with their own diff)
if [ -n "${GITHUB_REF_NAME:-}" ]; then
    VERSION="${GITHUB_REF_NAME#v}"
elif TAG="$(git -C "$PROJECT_ROOT" describe --tags --exact-match 2>/dev/null)"; then
    VERSION="${TAG#v}"
else
    VERSION="$(date +%Y.%m.%d)+dev"
fi

# Cache directory for the python-build-standalone tarball so repeat
# builds don't re-download. ~30MB, persists across builds.
CACHE_DIR="$HOME/.cache/meroshare-build"
mkdir -p "$CACHE_DIR"

# ── Bundled Python config ────────────────────────────────────────────
# Pin to a specific python-build-standalone release for reproducible
# builds. Update by bumping these values; the URL is reconstructed
# below. Releases: https://github.com/astral-sh/python-build-standalone/releases
PY_VERSION="3.12.7"
PY_TAG="20241016"

ARCH=$(uname -m)
case "$ARCH" in
    arm64)  PY_ARCH="aarch64" ;;
    x86_64) PY_ARCH="x86_64" ;;
    *) echo "Unsupported arch: $ARCH"; exit 1 ;;
esac

PY_TARBALL="cpython-${PY_VERSION}+${PY_TAG}-${PY_ARCH}-apple-darwin-install_only.tar.gz"
PY_URL="https://github.com/astral-sh/python-build-standalone/releases/download/${PY_TAG}/${PY_TARBALL}"

cd "$PROJECT_ROOT"

# ── Clean ────────────────────────────────────────────────────────────
echo "→ Cleaning build/ and dist/"
rm -rf "$BUILD_DIR" "$DIST_DIR"
mkdir -p "$APP_BUNDLE/Contents/MacOS"
mkdir -p "$APP_BUNDLE/Contents/Resources/app"
mkdir -p "$DIST_DIR"

# ── Stage source files ───────────────────────────────────────────────
echo "→ Staging source"
rsync -a \
    --exclude='venv' \
    --exclude='__pycache__' \
    --exclude='.git' \
    --exclude='build' \
    --exclude='dist' \
    --exclude='*.dmg' \
    --exclude='logs' \
    --exclude='.applied_issues*' \
    --exclude='.capital_cache.json' \
    --exclude='accounts.json' \
    --exclude='config.json' \
    --exclude='.env' \
    --exclude='.DS_Store' \
    --exclude='node_modules' \
    --exclude='.playwright-mcp' \
    --exclude='.pytest_cache' \
    --exclude='.ruff_cache' \
    --exclude='docs' \
    "$PROJECT_ROOT/" "$APP_BUNDLE/Contents/Resources/app/"
chmod +x "$APP_BUNDLE/Contents/Resources/app/run.sh"

# Stamp the version into _version.py inside the bundle so the
# menu bar's update check has something to compare against.
echo "→ Stamping version: $VERSION"
cat > "$APP_BUNDLE/Contents/Resources/app/_version.py" <<PY_EOF
"""Application version. Generated by scripts/build_dmg.sh."""

__version__ = "$VERSION"
PY_EOF

# ── Download bundled Python ──────────────────────────────────────────
PY_CACHE="$CACHE_DIR/$PY_TARBALL"
if [ ! -f "$PY_CACHE" ]; then
    echo "→ Downloading bundled Python ($PY_ARCH, ~30MB)"
    curl -fL --progress-bar -o "$PY_CACHE.tmp" "$PY_URL"
    mv "$PY_CACHE.tmp" "$PY_CACHE"
else
    echo "→ Using cached Python: $PY_CACHE"
fi

PY_BUNDLE_DIR="$APP_BUNDLE/Contents/Resources/python"
mkdir -p "$PY_BUNDLE_DIR"
echo "→ Extracting Python into bundle"
# python-build-standalone install_only tarballs unpack to a top-level
# `python/` directory; --strip-components=1 flattens that out.
tar -xf "$PY_CACHE" -C "$PY_BUNDLE_DIR" --strip-components=1

PYTHON_BIN="$PY_BUNDLE_DIR/bin/python3"
if [ ! -x "$PYTHON_BIN" ]; then
    echo "ERROR: bundled Python missing at $PYTHON_BIN. Tarball layout changed?"
    exit 1
fi

# Rename the interpreter so Activity Monitor / ps show "MeroShare"
# instead of "python3". A symlink isn't enough: the macOS kernel
# resolves symlinks before recording the process's accounting name
# (ucomm), so the symlink approach leaves Activity Monitor showing
# "python3.12". A hardlink, by contrast, gives the new path its own
# directory entry pointing to the same inode — kernel records the
# path the process was exec'd with, so ucomm becomes "MeroShare".
#
# Hardlink works here because both names live on the same filesystem
# (inside the bundle). dyld's @executable_path resolves to bin/ for
# both names, so the relative .dylib lookup paths inside python3.12
# still find lib/python3.12/* correctly.
#
# Why this works for the Flask child too: menubar.py spawns Flask
# via subprocess.Popen([sys.executable, "app.py"]). Python's
# sys.executable returns the path the interpreter was *invoked*
# with — so if we invoke menubar.py via bin/MeroShare, the Flask
# child inherits "MeroShare" without any extra plumbing.
NAMED_PYTHON_BIN="$PY_BUNDLE_DIR/bin/MeroShare"
ln -f "$PY_BUNDLE_DIR/bin/python3.12" "$NAMED_PYTHON_BIN"

# Sanity check the bundled Python before relying on it for pip.
"$PYTHON_BIN" -c "import sys; print('  bundled Python:', sys.version.split()[0])"

# ── Install Python dependencies into the bundle ──────────────────────
# Run pip with --no-warn-script-location since the bundle's bin/ is
# not on the user's PATH (intentional). --no-cache-dir keeps the
# bundle small (no ~/.cache/pip detritus from the build machine).
echo "→ Installing Python dependencies (Flask, requests, Playwright, etc.)"
"$PYTHON_BIN" -m pip install \
    --quiet \
    --no-cache-dir \
    --no-warn-script-location \
    --upgrade pip
"$PYTHON_BIN" -m pip install \
    --quiet \
    --no-cache-dir \
    --no-warn-script-location \
    -r "$PROJECT_ROOT/requirements.txt"

# ── Strip __pycache__ and .pyc to shave a few MB off the bundle ──────
# Python recompiles on first import anyway; shipping .pyc just makes
# the .dmg larger and the build less reproducible.
echo "→ Stripping __pycache__"
find "$PY_BUNDLE_DIR" -type d -name __pycache__ -prune -exec rm -rf {} + 2>/dev/null || true
find "$PY_BUNDLE_DIR" -name '*.pyc' -delete 2>/dev/null || true

# ── Write the launcher executable ────────────────────────────────────
LAUNCHER_PATH="$APP_BUNDLE/Contents/MacOS/$APP_NAME"
echo "→ Writing launcher"
cat > "$LAUNCHER_PATH" <<'LAUNCHER_EOF'
#!/bin/bash
# MeroShare Auto-Apply launcher (bundled-Python, menu-bar build)
#
# This .app ships its own Python interpreter, all pip dependencies,
# and a menu bar status item. The user's affordance for the app is
# the menu bar item. There's no Dock icon (LSUIElement=true).
#
# Logs and runtime state go to ~/Library/Logs and ~/Library/Application
# Support so the bundle itself stays write-clean. That's both Apple
# convention AND lets the .app run unchanged when the bundle is on a
# read-only filesystem (e.g. directly from a mounted .dmg).

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
APP_DIR="$SCRIPT_DIR/../Resources/app"
# bin/MeroShare is a symlink we create at build time so Activity
# Monitor and `ps` show "MeroShare" instead of generic "python3".
# Fall back to the canonical name if the symlink is missing (e.g.
# legacy bundle from an older build).
PYTHON="$SCRIPT_DIR/../Resources/python/bin/MeroShare"
if [ ! -x "$PYTHON" ]; then
    PYTHON="$SCRIPT_DIR/../Resources/python/bin/python3"
fi

# Apple-recommended state locations. mkdir -p in the user's HOME
# is always writable, so this works whether the .app is in
# /Applications, ~/Downloads, or mounted from a .dmg.
APP_SUPPORT="$HOME/Library/Application Support/MeroShare Auto-Apply"
LOGS_DIR="$HOME/Library/Logs/MeroShare Auto-Apply"
mkdir -p "$APP_SUPPORT" "$LOGS_DIR"
PLAYWRIGHT_MARKER="$APP_SUPPORT/playwright-installed"

# Tell the Python side to put state files alongside the launcher's
# log dir instead of inside the bundle. accounts.py / app.py /
# auto_apply.py honor this env var (when set) and fall back to
# Path(__file__).parent for dev installs (./run.sh) where the
# project IS the data dir.
export MEROSHARE_DATA_DIR="$APP_SUPPORT"

# Sanity: the bundle's been gutted somehow.
if [ ! -x "$PYTHON" ]; then
    /usr/bin/osascript -e 'display dialog "MeroShare Auto-Apply is missing its bundled Python.\n\nRe-download the .dmg from your usual source." buttons {"OK"} default button 1 with icon stop'
    exit 1
fi
if [ ! -d "$APP_DIR" ] || [ ! -f "$APP_DIR/menubar.py" ]; then
    /usr/bin/osascript -e 'display dialog "MeroShare Auto-Apply is missing source files.\n\nRe-download the .dmg." buttons {"OK"} default button 1 with icon stop'
    exit 1
fi

# Detect "running from a read-only filesystem". Typically means the
# user double-clicked the .app while it was still inside the mounted
# .dmg. Tell them what to do instead of silently failing.
if ! ( touch "$APP_DIR/.write-test" 2>/dev/null && rm "$APP_DIR/.write-test" 2>/dev/null ); then
    /usr/bin/osascript <<'OS_EOF' >/dev/null 2>&1 || true
display dialog "MeroShare Auto-Apply needs to be installed first.

Drag the app icon onto the Applications folder (the arrow in the .dmg window points the way), then launch it from your Applications folder or Launchpad.

Running directly from the .dmg won't work because macOS mounts disk images read-only." buttons {"Open Applications folder", "Cancel"} default button 1 with icon caution
if button returned of result is "Open Applications folder" then
    do shell script "open /Applications"
end if
OS_EOF
    exit 1
fi

# If a menu bar instance is already running, the user is double-
# clicking again because they want the dashboard. Open localhost
# and exit — the browser handles "connection refused" gracefully
# while Flask cold-starts (which now happens automatically when
# menubar.py boots, no longer requires a click).
#
# The previous "kill stale menubar and respawn" branch caused a
# user-reported bug: during the first launch's 3-4 second cold-
# start window, the user often double-clicks the .app a second
# time (looking for visible feedback). The kill-respawn would
# tear down the in-progress first launch and start over — making
# the .app feel like it needs two clicks to open. Trusting the
# existing instance is simpler AND avoids the race.
EXISTING_MENUBAR_PID=$(/usr/bin/pgrep -f "[m]enubar.py" 2>/dev/null | head -1 || true)
if [ -n "$EXISTING_MENUBAR_PID" ]; then
    /usr/bin/open "http://localhost:5050" 2>/dev/null || true
    exit 0
fi

cd "$APP_DIR"

# First-launch Chromium install. Playwright Chromium is needed
# before any apply can succeed. Pre-install it now so the user
# isn't blocked when they hit "Run Check Now" later. The Terminal
# window is the most honest UX: the download is 150MB and takes a
# minute or two; better visible than mysterious.
PLAYWRIGHT_CACHE_DIR="$HOME/Library/Caches/ms-playwright"
if [ ! -f "$PLAYWRIGHT_MARKER" ] \
   || ! ls "$PLAYWRIGHT_CACHE_DIR"/chromium-* >/dev/null 2>&1; then
    APP_DIR_Q=$(printf '%q' "$APP_DIR")
    PYTHON_Q=$(printf '%q' "$PYTHON")
    MARKER_Q=$(printf '%q' "$PLAYWRIGHT_MARKER")
    /usr/bin/osascript <<OS_EOF
tell application "Terminal"
    activate
    do script "echo 'MeroShare Auto-Apply: one-time browser engine install (~150MB)…' && cd $APP_DIR_Q && $PYTHON_Q -m playwright install chromium && touch $MARKER_Q && echo '' && echo 'Setup complete. The menu bar icon (top-right) is your control surface. Close this Terminal when ready.'"
end tell
OS_EOF
fi

# Launch the menu bar app via exec so the Python interpreter
# REPLACES this launcher in the same process. Critical for the
# Dock icon: macOS associates the bundle's icon.icns with the
# .app's main-executable PID. The previous "nohup ... &" pattern
# detached Python from the launcher, leaving Python as an orphan
# whose Dock icon (when "Show in Dock" was toggled on) defaulted
# to a generic Python rocket. With exec, the Python process IS
# the .app's main executable: setActivationPolicy_(.regular)
# from the menu picks up icon.icns correctly, Activity Monitor
# shows "MeroShare Auto-Apply", and Cmd-Tab gets the right name.
exec "$PYTHON" menubar.py >"$LOGS_DIR/menubar.log" 2>&1
LAUNCHER_EOF
chmod +x "$LAUNCHER_PATH"

# ── Write Info.plist ─────────────────────────────────────────────────
INFO_PLIST="$APP_BUNDLE/Contents/Info.plist"
echo "→ Writing Info.plist"
cat > "$INFO_PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>$APP_NAME</string>
    <key>CFBundleDisplayName</key>
    <string>$APP_NAME</string>
    <key>CFBundleIdentifier</key>
    <string>com.meroshare.autoapply</string>
    <key>CFBundleVersion</key>
    <string>$VERSION</string>
    <key>CFBundleShortVersionString</key>
    <string>$VERSION</string>
    <key>CFBundleExecutable</key>
    <string>$APP_NAME</string>
    <key>CFBundleIconFile</key>
    <string>icon.icns</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleSignature</key>
    <string>????</string>
    <key>LSMinimumSystemVersion</key>
    <string>10.15</string>
    <!-- LSUIElement=true: this is a menu bar app. No Dock icon, no
         App Switcher (Cmd-Tab) entry. The status item is the user's
         affordance for the app. -->
    <key>LSUIElement</key>
    <true/>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>LSBackgroundOnly</key>
    <false/>
    <key>LSApplicationCategoryType</key>
    <string>public.app-category.finance</string>
</dict>
</plist>
EOF
/usr/bin/plutil -lint "$INFO_PLIST" >/dev/null

# ── Generate icon ────────────────────────────────────────────────────
echo "→ Building icon"
ICON_TMP="$BUILD_DIR/icon.iconset"
mkdir -p "$ICON_TMP"
cat > "$BUILD_DIR/icon-src.svg" <<'SVG_EOF'
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
  <rect width="512" height="512" rx="112" fill="#5b8def"/>
  <path d="M144 352V160l112 128 112-128v192" stroke="white" stroke-width="38" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
</svg>
SVG_EOF

icon_built=true
for size in 16 32 64 128 256 512; do
    /usr/bin/sips -s format png -z "$size" "$size" \
        "$BUILD_DIR/icon-src.svg" \
        --out "$ICON_TMP/icon_${size}x${size}.png" >/dev/null 2>&1 || icon_built=false
    if [ "$size" -le 256 ]; then
        double=$((size * 2))
        /usr/bin/sips -s format png -z "$double" "$double" \
            "$BUILD_DIR/icon-src.svg" \
            --out "$ICON_TMP/icon_${size}x${size}@2x.png" >/dev/null 2>&1 || icon_built=false
    fi
done
if [ "$icon_built" = true ]; then
    /usr/bin/iconutil -c icns "$ICON_TMP" \
        -o "$APP_BUNDLE/Contents/Resources/icon.icns" 2>/dev/null \
        && echo "  icon.icns built" \
        || echo "  iconutil failed; .app will use generic icon"
else
    echo "  sips failed (older macOS?); .app will use generic icon"
fi

# ── Generate menu bar icon ───────────────────────────────────────────
# Menu bar icons are 22×22pt (44×44 retina), monochrome on a
# transparent background, used as a "template" so macOS auto-inverts
# them for light/dark menu bars. We render a thin outline-only "M"
# from the same shape used elsewhere.
echo "→ Building menu bar icon"
cat > "$BUILD_DIR/menubar-src.svg" <<'SVG_EOF'
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 44 44">
  <path d="M8 34V10l14 18 14-18v24"
        stroke="black" stroke-width="5.5"
        stroke-linecap="round" stroke-linejoin="round" fill="none"/>
</svg>
SVG_EOF
MENUBAR_ICON="$APP_BUNDLE/Contents/Resources/app/static/menubar-icon.png"
mkdir -p "$(dirname "$MENUBAR_ICON")"
/usr/bin/sips -s format png -z 44 44 \
    "$BUILD_DIR/menubar-src.svg" \
    --out "$MENUBAR_ICON" >/dev/null 2>&1 \
    && echo "  menubar-icon.png built (44×44)" \
    || echo "  menu bar icon generation failed; menu bar will be text-only"

# ── Ad-hoc codesign the bundle ───────────────────────────────────────
# Even without an Apple Developer cert, ad-hoc signing (`-s -`)
# seals the bundle so macOS can detect tampering and so launchd
# treats the binary correctly. Gatekeeper still requires the user
# to right-click → Open on first launch, but signing avoids the
# secondary "this app crashed because the signature changed" path
# that hits when ad-hoc-running unsigned binaries on Apple Silicon.
echo "→ Ad-hoc codesigning"
/usr/bin/codesign --force --deep --sign - "$APP_BUNDLE" 2>&1 | tail -3 || {
    echo "  codesign failed (continuing. Bundle is still functional)"
}

# ── Smoke-test the bundle ────────────────────────────────────────────
echo "→ Validating bundle"
test -x "$LAUNCHER_PATH" || { echo "launcher not executable"; exit 1; }
test -f "$INFO_PLIST" || { echo "Info.plist missing"; exit 1; }
test -x "$PYTHON_BIN" || { echo "bundled python not executable"; exit 1; }
test -f "$APP_BUNDLE/Contents/Resources/app/app.py" || { echo "app.py missing"; exit 1; }
# Verify the bundled Python can import our key dependencies. Catches
# a botched pip install before the user discovers it on launch. rumps
# is mac-only and is what the launcher invokes (via menubar.py).
"$PYTHON_BIN" -c "import flask, requests, schedule, playwright, rumps; print('  imports OK')"

# Compile-time syntax check on every shipped .py so a typo doesn't
# get distributed only to surface as a SyntaxError on first launch.
# `compileall` walks the bundle's source tree, fails the build on
# any error, and we discard the .pyc files since `__pycache__` is
# stripped further down anyway.
echo "→ Syntax-checking bundled .py"
"$PYTHON_BIN" -m compileall -q -f "$APP_BUNDLE/Contents/Resources/app" \
    || { echo "  syntax error in bundled source"; exit 1; }
find "$APP_BUNDLE/Contents/Resources/app" -type d -name __pycache__ \
    -prune -exec rm -rf {} + 2>/dev/null || true

BUNDLE_SIZE=$(du -sh "$APP_BUNDLE" | cut -f1)
echo "  bundle size: $BUNDLE_SIZE"

# ── Build the .dmg ───────────────────────────────────────────────────
echo "→ Building $DMG_NAME"
DMG_STAGE="$BUILD_DIR/dmg-stage"
rm -rf "$DMG_STAGE"
mkdir -p "$DMG_STAGE"
# Use cp -R rather than mv so the build/ directory keeps the
# original .app. Useful when iterating on the launcher and
# re-running just the dmg step.
cp -R "$APP_BUNDLE" "$DMG_STAGE/"
ln -s /Applications "$DMG_STAGE/Applications"

# A double-clickable rescue script for the "damaged" Gatekeeper
# message that hits ad-hoc-signed apps after a browser download
# on macOS Sequoia+. Strips com.apple.quarantine from the installed
# .app and launches it. Lives inside the .dmg so users hitting the
# error have a one-click fix without opening Terminal.
RESCUE="$DMG_STAGE/If macOS says damaged — double-click me.command"
cat > "$RESCUE" <<'RESCUE_EOF'
#!/bin/bash
# Removes the macOS quarantine flag from the installed app and opens it.
# Needed because we ad-hoc-sign the bundle (no $99 Apple Developer ID).
# After running once, the app launches normally on every future click.

APP="/Applications/MeroShare Auto-Apply.app"
if [ ! -d "$APP" ]; then
    /usr/bin/osascript -e 'display dialog "MeroShare Auto-Apply isn'\''t in your Applications folder yet.\n\nDrag the app from this disk image into Applications first, then run this script." buttons {"OK"} default button 1 with icon caution'
    exit 1
fi
/usr/bin/xattr -dr com.apple.quarantine "$APP" 2>/dev/null || true
/usr/bin/open "$APP"
RESCUE_EOF
chmod +x "$RESCUE"

# Plain-text README in the .dmg explaining the same thing in case
# the user prefers reading to clicking.
cat > "$DMG_STAGE/READ ME FIRST.txt" <<'README_EOF'
MeroShare Auto-Apply — install
==============================

1. Drag "MeroShare Auto-Apply" onto the Applications folder.
2. Open Applications and double-click the app.

If macOS says: "MeroShare Auto-Apply.app is damaged and can't be
opened" — that's not real damage. macOS rejects ad-hoc-signed
apps that came through a browser download. To fix it once:

   • Double-click "If macOS says damaged — double-click me.command"
     (the file next to this README in the disk image), OR
   • Open Terminal and paste:
       xattr -dr com.apple.quarantine "/Applications/MeroShare Auto-Apply.app"

After that, the app opens normally on every future click. The
auto-updater handles future versions transparently — you only need
to do this once per install.
README_EOF

if command -v create-dmg >/dev/null 2>&1; then
    create-dmg \
        --volname "$APP_NAME" \
        --window-pos 200 120 \
        --window-size 600 400 \
        --icon-size 100 \
        --icon "$APP_NAME.app" 175 190 \
        --app-drop-link 425 190 \
        --no-internet-enable \
        "$DMG_PATH" \
        "$DMG_STAGE" 2>&1 | tail -3
else
    /usr/bin/hdiutil create \
        -volname "$APP_NAME" \
        -srcfolder "$DMG_STAGE" \
        -ov \
        -format UDZO \
        "$DMG_PATH" >/dev/null
fi

DMG_SIZE=$(du -h "$DMG_PATH" | cut -f1)
echo ""
echo "Done."
echo "  → $DMG_PATH ($DMG_SIZE)"
echo ""
echo "Distribute by sharing the .dmg file. The recipient does NOT need"
echo "Python. It's bundled. They will need ~150MB of internet on first"
echo "launch for the Playwright Chromium download (visible in Terminal)."
echo ""
echo "Gatekeeper: first-time users right-click the .app inside the"
echo ".dmg → Open → Open. After that, double-click works."
